apiVersion: v1
kind: Pod
metadata:
  namespace: voting-app
  name: postgres-pod
  labels:
    name: postgres-pod
    type: database
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        

