apiVersion: v1 
kind: Service
metadata:
  namespace: voting-app
  name: db
  labels:
    name: postgres-service
    type: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    type: database