apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: voting-app
  name: redis-deploy
  labels:
    name: redis-deploy
    type: caching-database
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      type: caching-database
  template:
    metadata:
      namespace: voting-app
      name: redis-pod
      labels:
        name: redis-pod
        type: caching-database
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
    