apiVersion: v1
kind: Pod
metadata:
  namespace: voting-app
  name: redis-pod
  labels:
    name: redis-pod
    type: caching-database
spec:
  containers:
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379

