apiVersion: v1
kind: Service
metadata:
  namespace: voting-app
  name: redis
  labels:
    name: redis-service
    type: database
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-pod
    type: caching-database