apiVersion: v1
kind: Service
metadata:
  namespace: voting-app
  name: result-service
  labels:
    name: result-service
    type: forntend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
  selector:
    name: result-app-pod
    type: forntend
