apiVersion: v1
kind: Pod
metadata:
  namespace: voting-app
  name: voting-app-pod
  labels:
    name: voting-app-pod
    type: forntend
spec:
  containers:
    - name: voting-app
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80

