apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: voting-app
  name: voting-app-deploy
  labels:
    name: voting-app-deploy
    type: forntend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app-pod
      type: forntend
  template:
    metadata:
      namespace: voting-app
      name: voting-app-pod
      labels:
        name: voting-app-pod
        type: forntend
    spec:
      containers:
        - name: voting-app
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80