apiVersion: v1
kind: Service
metadata:
  namespace: voting-app
  name: voting-service
  labels:
    name: voting-service
    type: forntend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    name: voting-app-pod
    type: forntend