apiVersion: v1
kind: Pod
metadata:
  namespace: voting-app
  name: worker-pod
  labels:
    name: worker-pod
    type: backend
spec:
  containers:
    - name: worker-pod
      image: kodekloud/examplevotingapp_worker:v2

